"""empty message

Revision ID: 5d1735a174ef
Revises: 
Create Date: 2021-04-24 15:46:28.784919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1735a174ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('datejoined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_car',
    sa.Column('car_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=29), nullable=True),
    sa.Column('colour', sa.String(length=225), nullable=True),
    sa.Column('year', sa.String(length=225), nullable=True),
    sa.Column('transmis', sa.String(length=225), nullable=True),
    sa.Column('car_type', sa.String(length=225), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('car_id')
    )
    op.create_table('user_fav',
    sa.Column('user_favid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_favid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_fav')
    op.drop_table('user_car')
    op.drop_table('user')
    # ### end Alembic commands ###
